### ISSUE TITLE
Allow borderless windows on Linux

### ISSUE THREAD

**Issue by aknarts** [AchetaGames/UnrealEngineChanges#13]
https://github.com/EpicGames/UnrealEngine/pull/5877

**Comment by mastercoms** [comment]
Resolved, https://github.com/EpicGames/UnrealEngine/pull/5877#issuecomment-920088387

**Comment by aknarts** [comment]
> Resolved, [EpicGames/UnrealEngine#5877 (comment)](https://github.com/EpicGames/UnrealEngine/pull/5877#issuecomment-920088387)

Thanks, I need to fix the automation that should have closed this on its own.
